version: '3.9'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: PizzaDb
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - mysql
    environment:
      ConnectionStrings__WebApiDatabase: "server=mysql; database=PizzaDb; user=root; password=abc123"
    ports:
      - "5001:80"
      - "5000:8090"

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - api
    environment:
      API_URL: "http://api:80"
    ports:
      - "4200:4200"
